export enum repositoryActionTypes {
    FETCH_GET_REQUEST = "FETCH_GET_REQUEST",
    FETCH_GET_SUCCESS = "FETCH_GET_SUCCESS",
    FETCH_GET_FAILURE = "FETCH_GET_FAILURE",
    FETCH_SINGLE_REPOSITORY_REQUEST="FETCH_SINGLE_REPOSITORY_REQUEST",
    FETCH_SINGLE_REPOSITORY_SUCCESS="FETCH_SINGLE_REPOSITORY_SUCCESS",
    FETCH_SINGLE_REPOSITORY_FAILURE="FETCH_SINGLE_REPOSITORY_FAILUR",
    SORT_REPOSITORIES_BY_STRING="SORT_REPOSITORIES_BY_STRING",
    SORT_REPOSITORIES_BY_NUMBER="SORT_REPOSITORIES_BY_NUMBER"
  }